version: "3.1"
services:
  db-4cadia:
    image: mongo:4.2
    container_name: db-4cadia
    # restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
        - net-4cadia

  api-4cadia:
    image: node:10.14.0
    container_name: api-4cadia
    # restart: always
    env_file:
     - .env
    depends_on:
      - db-4cadia
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
        - net-4cadia
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm start" 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  net-4cadia:
    external:
      name: net-4cadia
volumes:
  mongodbdata:
    driver: local